services:
  portfolio:
    container_name: portfolio
    build:
      dockerfile: ./Dockerfile
      context: .
      target: portfolio
    ports:
      - 4321:4321
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUBLIC_API_URL: http://host.docker.internal:8000/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`akmalkeisin.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=le"
networks:
  proxy:
    name: traefik-proxy
    external: true
